export const dcTrack_ENDPOINTS = {
  Cabinet: {
    tiName: "",
    cmbMake: "",
    cmbModel: "",
    cmbLocation: "",
    cmbRowPosition: "",
    radioFrontFaces: "",
    tiAssetTag: "",
    tiSerialNumber: "",
    cmbStatus: "",
    id: "",
    tiClass: "",
    tiDataPortCount: "",
    tiLocationName: "",
    tiRUs: "",
    tiRackUnits: "",
  },

  "Device / Standard": {
    tiName: "",
    cmbMake: "",
    cmbModel: "",
    cmbLocation: "",
    cmbCabinet: "",
    cmbUPosition: "",
    cmbOrientation: "",
    radioRailsUsed: "",
    tiAssetTag: "",
    tiSerialNumber: "",
    cmbStatus: "",
    id: "",
    tiClass: "",
    tiMounting: "",
    tiRUs: "",
    tiRackUnits: "",
    tiSubclass: "",
  },
  "Rack PDU / AC Power": {
    tiName: "",
    cmbMake: "",
    cmbModel: "",
    cmbLocation: "",
    tiLocationName: "",
    cmbCabinet: "",
    cmbUPosition: "",
    radioCabinetSide: "",
    radioDepthPosition: "",
    tiAssetTag: "",
    tiSerialNumber: "",
    cmbStatus: "",
    cmbPowerPortQuantity: "",
    id: "",
    tiClass: "",
    tiDataPortCount: "",
    tiRUs: "",
    tiRackUnits: "",
    tiSubclass: "",
  },
  "Network / Blade": {
    tiName: "",
    cmbMake: "",
    cmbModel: "",
    cmbLocation: "",
    tiLocationName: "",
    cmbCabinet: "",
    cmbChassis: "",
    radioChassisFace: "",
    cmbSlotPosition: "",
    tiAssetTag: "",
    tiSerialNumber: "",
    cmbStatus: "",
    id: "",
    tiClass: "",
    tiFormFactor: "",
    tiDataPortCount: "",
    tiRUs: "",
    tiRackUnits: "",
    tiSubclass: "",
  },
};
