export const dcTrack_EDITABLE = {
  "Rack PDU / AC Power": {
    cmbCabinet: true,
    cmbLocation: true,
    cmbMake: true,
    cmbModel: true,
    cmbPowerPortQuantity: true,
    cmbStatus: true,
    cmbUPosition: true,
    id: true,
    radioCabinetSide: true,
    radioDepthPosition: true,
    tiClass: false,
    tiDataPortCount: false,
    tiLocationName: true,
    tiName: true,
    tiRUs: false,
    tiRackUnits: false,
    tiSubclass: false,
    tiAssetTag: true,
    tiSerialNumber: true,
  },
  "Device / Standard": {
    cmbCabinet: true,
    cmbLocation: true,
    cmbMake: true,
    cmbModel: true,
    cmbOrientation: true,
    cmbStatus: true,
    cmbUPosition: true,
    id: true,
    radioRailsUsed: true,
    tiClass: false,
    tiMounting: false,
    tiName: true,
    tiRUs: false,
    tiRackUnits: false,
    tiSubclass: false,
    tiAssetTag: true,
    tiSerialNumber: true,
  },
  Cabinet: {
    cmbLocation: true,
    cmbMake: true,
    cmbModel: true,
    cmbRowPosition: true,
    cmbStatus: true,
    id: true,
    radioFrontFaces: true,
    tiClass: false,
    tiDataPortCount: false,
    tiLocationName: true,
    tiName: true,
    tiRUs: false,
    tiRackUnits: false,
    tiAssetTag: true,
    tiSerialNumber: true,
  },
};
