export const dcTrack_COPY_REQUIRED = {
  Cabinet: {
    tiName: true,
    cmbMake: false,
    cmbModel: false,
    cmbLocation: false,
    cmbRowPosition: true,
    radioFrontFaces: true,
    tiAssetTag: true,
    tiSerialNumber: true,
    cmbStatus: false,
    id: true,
    tiClass: false,
    tiDataPortCount: false,
    tiLocationName: false,
    tiRUs: false,
    tiRackUnits: false,
  },

  "Device / Standard": {
    tiName: true,
    cmbMake: false,
    cmbModel: false,
    cmbLocation: false,
    cmbCabinet: false,
    cmbUPosition: true,
    cmbOrientation: false,
    radioRailsUsed: false,
    tiAssetTag: true,
    tiSerialNumber: true,
    cmbStatus: false,
    id: true,
    tiClass: false,
    tiMounting: false,
    tiRUs: false,
    tiRackUnits: false,
    tiSubclass: false,
  },

  "Rack PDU / AC Power": {
    tiName: true,
    cmbMake: false,
    cmbModel: false,
    cmbLocation: false,
    tiLocationName: false,
    cmbCabinet: false,
    cmbUPosition: true,
    radioCabinetSide: true,
    radioDepthPosition: true,
    tiAssetTag: true,
    tiSerialNumber: true,
    cmbStatus: false,
    cmbPowerPortQuantity: false,
    id: true,
    tiClass: false,
    tiDataPortCount: false,
    tiRUs: false,
    tiRackUnits: false,
    tiSubclass: false,
  },

  "Network / Blade": {
    tiName: true,
    cmbMake: false,
    cmbModel: false,
    cmbLocation: false,
    tiLocationName: false,
    cmbCabinet: false,
    cmbChassis: true,
    radioChassisFace: true,
    cmbSlotPosition: true,
    tiAssetTag: true,
    tiSerialNumber: true,
    cmbStatus: false,
    id: true,
    tiClass: false,
    tiFormFactor: false,
    tiDataPortCount: false,
    tiRUs: false,
    tiRackUnits: false,
    tiSubclass: false,
  },
};
