export const dcTrack_APIREQUIRED = {
  "Rack PDU / AC Power": {
    cmbCabinet: true,
    cmbLocation: true,
    cmbMake: true,
    cmbModel: true,
    cmbPowerPortQuantity: false,
    cmbStatus: false,
    cmbUPosition: true,
    id: false,
    radioCabinetSide: true,
    radioDepthPosition: true,
    tiClass: false,
    tiDataPortCount: false,
    tiLocationName: false,
    tiName: true,
    tiRUs: false,
    tiRackUnits: false,
    tiSubclass: false,
    tiAssetTag: false,
    tiSerialNumber: false,
  },

  "Device / Standard": {
    cmbCabinet: true,
    cmbLocation: true,
    cmbMake: true,
    cmbModel: true,
    cmbOrientation: true,
    cmbStatus: false,
    cmbUPosition: true,
    id: false,
    radioRailsUsed: true,
    tiClass: false,
    tiMounting: false,
    tiName: true,
    tiRUs: false,
    tiRackUnits: false,
    tiSubclass: false,
    tiAssetTag: false,
    tiSerialNumber: false,
  },

  Cabinet: {
    cmbLocation: true,
    cmbMake: true,
    cmbModel: true,
    cmbRowPosition: false,
    cmbStatus: false,
    id: false,
    radioFrontFaces: false,
    tiClass: false,
    tiDataPortCount: false,
    tiLocationName: false,
    tiName: true,
    tiRUs: false,
    tiRackUnits: false,
    tiAssetTag: false,
    tiSerialNumber: false,
  },

  "Network / Blade": {
    cmbCabinet: true,
    cmbLocation: true,
    cmbMake: true,
    cmbModel: true,
    cmbChassis: true,
    cmbSlotPosition: true,
    cmbStatus: false,
    id: false,
    radioChassisFace: true,
    tiName: true,
    tiClass: false,
    tiDataPortCount: false,
    tiLocationName: false,
    tiRUs: false,
    tiRackUnits: false,
    tiSubclass: false,
    tiAssetTag: false,
    tiSerialNumber: false,
    tiFormFactor: false,
  },
};
