export const dcTrack_READABLE = {
  "Rack PDU / AC Power": {
    cmbCabinet: "Cabinet Name",
    cmbLocation: "Location Name",
    cmbMake: "Make Name",
    cmbModel: "Model Name",
    cmbPowerPortQuantity: "Port Count",
    cmbStatus: "Item Status",
    cmbUPosition: "U Position",
    id: "ID Value",
    radioCabinetSide: "Side Label",
    radioDepthPosition: "Depth Label",
    tiClass: "Class Name",
    tiDataPortCount: "Data Ports",
    tiLocationName: "Location Label",
    tiName: "Item Name",
    tiRUs: "RU Count",
    tiRackUnits: "Rack Units",
    tiSubclass: "Sub Class",
    tiAssetTag: "Asset Tag",
    tiSerialNumber: "Serial Number",
  },

  "Device / Standard": {
    cmbCabinet: "Cabinet Name",
    cmbLocation: "Location Name",
    cmbMake: "Make Name",
    cmbModel: "Model Name",
    cmbOrientation: "Orientation Type",
    cmbStatus: "Item Status",
    cmbUPosition: "U Position",
    id: "ID Value",
    radioRailsUsed: "Rails Used",
    tiClass: "Class Name",
    tiMounting: "Mount Type",
    tiName: "Item Name",
    tiRUs: "RU Count",
    tiRackUnits: "Rack Units",
    tiSubclass: "Sub Class",
    tiAssetTag: "Asset Tag",
    tiSerialNumber: "Serial Number",
  },

  Cabinet: {
    cmbLocation: "Location Name",
    cmbMake: "Make Name",
    cmbModel: "Model Name",
    cmbRowPosition: "Row Position",
    cmbStatus: "Item Status",
    id: "ID Value",
    radioFrontFaces: "Front Faces",
    tiClass: "Class Name",
    tiDataPortCount: "Data Ports",
    tiLocationName: "Location Label",
    tiName: "Cabinet Name",
    tiRUs: "RU Count",
    tiRackUnits: "Rack Units",
    tiAssetTag: "Asset Tag",
    tiSerialNumber: "Serial Number",
  },

  "Network / Blade": {
    cmbCabinet: "Cabinet Name",
    cmbLocation: "Location Name",
    cmbMake: "Make Name",
    cmbModel: "Model Name",
    cmbChassis: "Chassis Name",
    cmbSlotPosition: "Slot Position",
    cmbStatus: "Item Status",
    id: "ID Value",
    radioChassisFace: "Chassis Face",
    tiName: "Blade Name",
    tiClass: "Class Name",
    tiDataPortCount: "Data Ports",
    tiLocationName: "Location Label",
    tiRUs: "RU Count",
    tiRackUnits: "Rack Units",
    tiSubclass: "Sub Class",
    tiAssetTag: "Asset Tag",
    tiSerialNumber: "Serial Number",
    tiFormFactor: "Form Factor",
  },
};
