export const dcTrack_INPUTTYPES = {
  "Rack PDU / AC Power": {
    cmbCabinet: "CABINET",
    cmbLocation: "LOCATION",
    cmbMake: "IMGMake",
    cmbModel: "IMGModel",
    cmbPowerPortQuantity: "Number",
    cmbStatus: "String",
    cmbUPosition: "UPosition",
    id: "String",
    radioCabinetSide: "CABINETSIDE",
    radioDepthPosition: "DEPTHPOSITION",
    tiClass: "Object",
    tiDataPortCount: "Number",
    tiLocationName: "ORC",
    tiName: "ORC",
    tiRUs: "Number",
    tiRackUnits: "Number",
    tiSubclass: "String",
    tiAssetTag: "QR",
    tiSerialNumber: "QR",
  },
  "Device / Standard": {
    cmbCabinet: "CABINET",
    cmbLocation: "LOCATION",
    cmbMake: "IMGMake",
    cmbModel: "IMGModel",
    cmbOrientation: "String",
    cmbStatus: "String",
    cmbUPosition: "UPosition",
    id: "String",
    radioRailsUsed: "String",
    tiClass: "Object",
    tiMounting: "String",
    tiName: "ORC",
    tiRUs: "Number",
    tiRackUnits: "Number",
    tiSubclass: "String",
    tiAssetTag: "QR",
    tiSerialNumber: "QR",
  },
  Cabinet: {
    cmbLocation: "LOCATION",
    cmbMake: "IMGMake",
    cmbModel: "IMGModel",
    cmbRowPosition: "Number",
    cmbStatus: "String",
    id: "String",
    radioFrontFaces: "Number",
    tiClass: "Object",
    tiDataPortCount: "Number",
    tiLocationName: "ORC",
    tiName: "ORC",
    tiRUs: "Number",
    tiRackUnits: "Number",
    tiAssetTag: "QR",
    tiSerialNumber: "QR",
  },
};
