export const dcTrack_DISCRIPTIONS = {
  "Rack PDU / AC Power": {
    cmbCabinet: "Cabinet name where the PDU sits inside the layout",
    cmbLocation: "Location name that links the PDU to a site or room",
    cmbMake: "Vendor name shown in the dcTrack model library",
    cmbModel: "Model label provided by the vendor",
    cmbPowerPortQuantity: "Total outlet count used during power planning",
    cmbStatus: "Current state used in workflows like planned or active",
    cmbUPosition: "Mount point used for tracking vertical placement",
    id: "System ID used to reference the PDU in API requests",
    radioCabinetSide: "Side of the cabinet used to position the PDU",
    radioDepthPosition: "Depth position used for front or center alignment",
    tiClass: "Item class assigned by dcTrack for this type of hardware",
    tiDataPortCount: "Number of structured data ports on the device",
    tiLocationName: "Readable form of the linked location",
    tiName: "Published PDU label used in the cabinet map",
    tiRUs: "Rack unit size that controls vertical space",
    tiRackUnits: "Rack unit count from the model record",
    tiSubclass: "Subtype used for reporting inside the class group",
    tiAssetTag: "Tracking tag used for audits and asset reports",
    tiSerialNumber: "Serial value recorded for identification",
  },

  "Device / Standard": {
    cmbCabinet: "Cabinet name where the device is installed",
    cmbLocation: "Location name tied to this device",
    cmbMake: "Vendor name provided in the model record",
    cmbModel: "Model label displayed in item details",
    cmbOrientation: "Facing direction used for airflow and layout rules",
    cmbStatus: "Current lifecycle state recorded for the device",
    cmbUPosition: "Rack unit position where the device starts",
    id: "System ID used to reference the device in API calls",
    radioRailsUsed: "Rail choice used for mounting in the rack",
    tiClass: "Primary class used to group this item in dcTrack",
    tiMounting: "Mount type recorded from the model record",
    tiName: "Device label shown in cabinet views and reports",
    tiRUs: "Rack unit height of the device",
    tiRackUnits: "Rack unit value stored in the model record",
    tiSubclass: "Subtype used for finer classification",
    tiAssetTag: "Tracking tag used for audits and asset reports",
    tiSerialNumber: "Serial value used to identify the device",
  },

  Cabinet: {
    cmbLocation: "Location name tied to the cabinet record",
    cmbMake: "Vendor of the physical cabinet",
    cmbModel: "Model of the cabinet stored in dcTrack",
    cmbRowPosition: "Index value used to place the cabinet in a row",
    cmbStatus: "Lifecycle state recorded for the cabinet",
    id: "System ID used to reference the cabinet in the API",
    radioFrontFaces: "Direction the cabinet front faces inside the room",
    tiClass: "Item class assigned for cabinets in dcTrack",
    tiDataPortCount: "Count of all structured cabling ports",
    tiLocationName: "Readable form of the linked location",
    tiName: "Cabinet label used across maps and reports",
    tiRUs: "Total rack units available",
    tiRackUnits: "Rack unit count stored in the model record",
    tiAssetTag: "Tracking tag used for audits and asset records",
    tiSerialNumber: "Serial value used to identify the cabinet",
  },

  "Network / Blade": {
    cmbCabinet: "Cabinet name where the chassis is installed",
    cmbLocation: "Location name linked to the blade through the chassis",
    cmbMake: "Vendor name sourced from the blade model",
    cmbModel: "Model label of the blade installed in the chassis",
    cmbChassis: "Chassis name that the blade sits inside",
    cmbSlotPosition: "Slot index used to place the blade in the chassis",
    cmbStatus: "Lifecycle state recorded for the blade item",
    id: "System ID used to reference the blade in the API",
    radioChassisFace: "Face of the chassis where the blade inserts",
    tiClass: "Classification used inside the Network class group",
    tiDataPortCount: "Number of data ports available on the blade",
    tiLocationName: "Readable form of the linked location",
    tiName: "Blade label shown in the chassis map",
    tiRUs: "Rack unit value passed through from the model",
    tiRackUnits: "Rack unit data stored in the blade model",
    tiSubclass: "Subtype used to group blade types",
    tiAssetTag: "Tracking tag used for audits and asset reports",
    tiSerialNumber: "Serial value used to identify the blade",
    tiFormFactor: "Physical form factor of the blade hardware",
  },
};
