export const apiUrls = {
  Locations: "/v1/locations",
  "Aisles and Rows": "/v1/sublocations",
  Cabinets: "/v2/dcimoperations/items",
  "Rack PDUs": "/v2/dcimoperations/items",
  Devices: "/v2/dcimoperations/items",
  Power: "/v2/dcimoperations/powerconnections",
  "Structure Cabling": "/v2/dcimoperations/dataconnections",
  "Data Connections": "/v2/dcimoperations/dataconnections",
  "Add Power Panels": "/v2/dcimoperations/panels",
  "Add Breakers & Outlets": "/v2/dcimoperations/breakers",
  "Data, Power & Sensor Ports": "/v2/dcimoperations/ports",
  "Add Parts": "/v2/dcimoperations/parts",
};

export const headerEndpoints = {
  Locations: {
    "# Operation ": "",
    "Object ": "objectType",
    "dcTrack Location Code": "tiLocationCode",
    "dcTrack Location Name": "tiLocationName",
    "dcTrack Location Hierarchy": "cmbHierarchyLevel",
    "dcTrack Location Parent": "tiParentLocationCode",
    "Can Contain Assets": "chkContainsAssets",
    "Data Center Area": "tiLocationArea",
    Country: "cmbAddressCountry",
    "Enable AC Virtual Power Chain": "chkEnableVpcAcPower",
    "Enable DC Virtual Power Chain": "chkEnableVpcDcPower",
    "Is Default Location": "cbDefaultSite",
    "Capacity(kW)": "tiPowerCapacitykW",
  },

  "Aisles and Rows": {
    "# Operation ": "",
    "Object ": "objectType",
    "Sub Location Name": "tiSubLocationName",
    "Location  ": "cmbLocation",
    "Sub Location Type": "cmbSubLocationType",
    "Parent Sub Location": "tiParentSubLocationCode",
    "Capacity(kW)": "tiPowerCapacitykW",
  },

  Cabinets: {
    "# Operation ": "",
    "Object ": "objectType",
    "Name ": "tiName",
    "Make ": "cmbMake",
    "Model ": "cmbModel",
    "Part Number": "tiPartNumber",
    "Location  ": "cmbLocation",
    "Location Name": "tiLocationName",
    "Front Faces": "radioFrontFaces",
    "Aisle Label  ": "cmbRowLabel",
    "Row Label   ": "cmbRowLabel",
    "Position in Row    ": "cmbRowPosition",
    Status: "cmbStatus",
    "Power Capacity (kW)": "tiPowerCapacity",
    "Weight Capacity": "tiLoadCapacity",
  },

  "Rack PDUs": {
    "# Operation ": "",
    "Object ": "objectType",
    "Name ": "tiName",
    "Make ": "cmbMake",
    "Model ": "cmbModel",
    "Part Number": "tiPartNumber",
    "Location  ": "cmbLocation",
    "Location Name": "tiLocationName",
    "Cabinet ": "cmbCabinet",
    "Depth Position ": "radioDepthPosition",
    "Cabinet Side ": "radioCabinetSide",
    "U Position ": "cmbUPosition",
    "IP Address": "ipAddressPortName",
    "IP Address Port Name": "ipAddressPortName",
    "SNMP Write Community String": "tiSnmpWriteCommString",
    "User Name": "tiSnmpV3Username",
    Password: "tiPXPassword",
    Status: "cmbStatus",
  },

  Devices: {
    "# Operation ": "",
    "Object ": "objectType",
    "Name ": "tiName",
    "Make ": "cmbMake",
    "Model ": "cmbModel",
    "Part Number": "tiPartNumber",
    "Location  ": "cmbLocation",
    "Location Name": "tiLocationName",
    "Asset Tag": "tiAssetTag",
    "Serial Number": "tiSerialNumber",
    "Cabinet ": "cmbCabinet",
    "U Position ": "cmbUPosition",
    "Chassis ": "cmbChassis",
    "Chassis Face ": "radioChassisFace",
    "Slot Position ": "cmbSlotPosition",
    "Is VM Host": "cmbVMHostItem",
    "VM Cluster": "cmbVMCluster",
    Status: "cmbStatus",
  },

  Power: {
    "# Operation ": "",
    "Object ": "objectType",
    "Starting Item Location  ": "startingItemLocation",
    "Starting Item Name ": "startingItemName",
    "Starting Port Name  ": "startingPortName",
    "Cord Type": "cordType",
    "Cord ID": "cordId",
    "Cord Color": "cordColor",
    "Cord Length (ft/m)": "cordLength",
    "Length Units": "lengthUnit",
    "Ending Item Location ": "endingItemLocation",
    "Ending Item Name  ": "endingItemName",
    "Ending Port Name  ": "endingPortName",
    "CIRCUIT ID": "circuitId",
    "Contact Team": "contactTeam",
    Contact: "contact",
    Notes: "notes",
  },

  "Structure Cabling": {
    "# Operation ": "",
    "Object ": "objectType",
    "Starting Item Location ": "startingItemLocation",
    "Starting Item Name ": "startingItemName",
    "Starting Port Name  ": "startingPortName",
    "Starting Port Index": "startingPortIndex",
    "Starting Port Connector   ": "startingConnector",
    "Cable Grade  ": "cableGrade",
    Media: "mediaType",
    "Length (ft/m) ": "cableLength",
    "Length Units": "lengthUnit",
    Color: "cableColor",
    Group: "cableGroup",
    "Ending  Item Location": "endingItemLocation",
    "Ending Item Name  ": "endingItemName",
    "Ending Port Name  ": "endingPortName",
    "Ending Port Index": "endingPortIndex",
    "Ending Port Connector   ": "endingConnector",
  },

  "Data Connections": {
    "# Operation ": "",
    "Object ": "objectType",
    "Starting Item Location  ": "startingItemLocation",
    "Starting Item Name ": "startingItemName",
    "Starting Port Name  ": "startingPortName",
    "Cord 1 Type": "cordType",
    "Cord 1 ID": "cordId",
    "Cord 1 Color": "cordColor",
    "Cord 1 Length( ft/m)": "cordLength",
    "Length Units": "lengthUnit",
    "Ending Item Location ": "endingItemLocation",
    "Ending Item Name  ": "endingItemName",
    "Ending Port Name  ": "endingPortName",
    "CIRCUIT ID": "circuitId",
    "Contact Team": "contactTeam",
    Contact: "contact",
    Notes: "notes",
  },

  "Add Power Panels": {
    "# Operation ": "",
    "Object ": "objectType",
    "Floor PDU ": "cmbFloorPDU",
    "Name ": "tiName",
    "Location  ": "cmbLocation",
    "Location Name": "tiLocationName",
    "Phases ": "phase",
    "Phase Voltage ": "phaseVoltage",
    "Wire Colors ": "phaseAColor",
    "Rating (A)": "ratingAmps",
    "No of Poles ": "panelPolesQty",
    "Panel Layout ": "panelLayout",
    "Pole Numbering ": "poleNumbering",
    "First Pole Number": "firstPoleNumber",
    Mirrored: "cbPropagate",
  },

  "Add Breakers & Outlets": {
    "# Operation ": "",
    "Object ": "objectType",
    "Panel Type": "panelType",
    "Floor PDU ": "cmbFloorPDU",
    Make: "cmbMake",
    Model: "cmbModel",
    "Panel ": "panelSource",
    "Location ": "cmbLocation",
    "Starting Pole No  ": "firstPoleNumber",
    "No of Poles": "panelPolesQty",
    "Rated Amps": "ratingAmps",
    "Measured Amps": "tiRectifiersActualLoadAmps",
    "Power Outlet Location": "tiLocationName",
    "Power Outlet Row": "cmbRowLabel",
    "Power Outlet Position in Row": "cmbRowPosition",
    "Power Outlet Connector": "tiPortNamePrefix",
    "Power Outlet Cabinet": "cmbCabinet",
    "Power Outlet Position": "cmbUPosition",
  },

  "Data, Power & Sensor Ports": {
    "# Operation ": "",
    "Object ": "objectType",
    "Item Location  ": "cmbLocation",
    "Item Name ": "tiName",
    "Port Name  ": "portName",
    "Index ": "portIndex",
    "Port Type": "portType",
    "In Use": "used",
    "Color Code": "colorCode",
    "Grouping/VLAN": "grouping",
    "MAC Address": "macAddress",
    "IP Address": "ipAddress",
    "Connector  ": "connectorName",
    "Media  ": "mediaType",
    "Protocol  ": "protocol",
    "Data Rate  ": "dataRate",
    Comment: "comments",
  },

  "Add Parts": {
    "# Operation ": "",
    "Object ": "objectType",
    "Serial/Asset/Batch Number ": "serialNumber",
    "Make ": "cmbMake",
    "Model ": "cmbModel",
    "Part Number ": "partNumber",
    "Storage Location  ": "storageLocation",
    "Tracking ": "trackingMethod",
    Description: "description",
    "Count in Stock ": "countInStock",
    "Count in Use ": "countInUse",
    "Threshold ": "thresholdQty",
    "Status ": "status",
    "Date of Manufacture": "manufactureDate",
    "Date Format": "dateFormat",
    "Threshold Contacts": "thresholdContacts",
  },
};

export const required_master = {
  "# Operation ": true,
  "Object ": true,
  "dcTrack Location Code": true,
  "dcTrack Location Name": true,
  "dcTrack Location Hierarchy": true,
  "dcTrack Location Parent": true,
  "Can Contain Assets": false,
  "Data Center Area": true,
  Country: true,
  "Enable AC Virtual Power Chain": false,
  "Enable DC Virtual Power Chain": false,
  "Is Default Location": false,
  "Capacity(kW)": false,

  "Sub Location Name": true,
  "Location  ": true,
  "Sub Location Type": true,
  "Parent Sub Location": false,

  "Name ": true,
  "Make ": true,
  "Model ": true,
  "Part Number": false,
  "Location Name": false,
  "Front Faces": false,
  "Aisle Label  ": false,
  "Row Label   ": true,
  "Position in Row    ": true,
  Status: false,
  "Power Capacity (kW)": false,
  "Weight Capacity": false,

  "Cabinet ": true,
  "Depth Position ": true,
  "Cabinet Side ": true,
  "U Position ": true,
  "IP Address": false,
  "IP Address Port Name": false,
  "SNMP Write Community String": false,
  "User Name": false,
  Password: false,

  "Asset Tag": false,
  "Serial Number": false,
  "Chassis ": true,
  "Chassis Face ": true,
  "Slot Position ": true,
  "Is VM Host": false,
  "VM Cluster": false,

  "Starting Item Location  ": true,
  "Starting Item Name ": true,
  "Starting Port Name  ": true,
  "Cord Type": false,
  "Cord ID": false,
  "Cord Color": false,
  "Cord Length (ft/m)": false,
  "Length Units": false,
  "Ending Item Location ": true,
  "Ending Item Name  ": true,
  "Ending Port Name  ": true,
  "CIRCUIT ID": false,
  "Contact Team": false,
  Contact: false,
  Notes: false,

  "Starting Item Location ": true,
  "Starting Item Name ": true,
  "Starting Port Name  ": true,
  "Starting Port Index": false,
  "Starting Port Connector   ": true,
  "Cable Grade  ": true,
  Media: true,
  "Length (ft/m) ": true,
  Color: false,
  Group: false,
  "Ending  Item Location": true,
  "Ending Item Name  ": true,
  "Ending Port Name  ": true,
  "Ending Port Index": false,
  "Ending Port Connector   ": true,

  "Cord 1 Type": false,
  "Cord 1 ID": false,
  "Cord 1 Color": false,
  "Cord 1 Length( ft/m)": false,

  "Floor PDU ": true,
  "Phases ": true,
  "Phase Voltage ": true,
  "Wire Colors ": true,
  "Rating (A)": true,
  "No of Poles ": true,
  "Panel Layout ": true,
  "Pole Numbering ": true,
  "First Pole Number": false,
  Mirrored: false,

  "Panel Type": true,
  "Panel ": true,
  "Starting Pole No  ": true,
  "No of Poles": true,
  "Rated Amps": true,
  "Measured Amps": false,
  "Power Outlet Location": false,
  "Power Outlet Row": false,
  "Power Outlet Position in Row": false,
  "Power Outlet Connector": false,
  "Power Outlet Cabinet": false,
  "Power Outlet Position": false,

  "Item Location  ": true,
  "Item Name ": true,
  "Port Name  ": true,
  "Index ": false,
  "Port Type": true,
  "In Use": false,
  "Color Code": false,
  "Grouping/VLAN": false,
  "MAC Address": false,
  "IP Address": false,
  "Connector  ": true,
  "Media  ": true,
  "Protocol  ": true,
  "Data Rate  ": true,
  Comment: false,

  "Serial/Asset/Batch Number ": true,
  "Storage Location  ": true,
  "Tracking ": true,
  Description: false,
  "Count in Stock ": true,
  "Count in Use ": true,
  "Threshold ": true,
  "Status ": true,
  "Date of Manufacture": false,
  "Date Format": false,
  "Threshold Contacts": false,
};
