// REMOVED_ITEM_TEMPLATE used to pull the not needed keys from the returned API
// https://10.34.2.111/api/v2/dcimoperations/items/{id}

const REMOVED_ITEM_TEMPLATE = {
  _tiProceedOnWarning: false,
  _whenMoveItemId: 0,
  chkReconciled: true,
  chkValid: true,
  cmbLastUpdatedBy: "jamaer",
  cmbPowerPortQuantity: 0,
  cmbSnmpV3Enabled: false,
  lastUpdatedOn: "2025-11-20 08:20:04-05",
  modelId: 165,
  origin: "API",
  proxyIndex: 0,
  sysCreationDate: "2025-11-20 08:20:03-05",
  tiContractAmount: 0.0,
  tiDimension: "73.5 X 24.0 X 30.0",
  tiDepth: 30.0,
  tiFormFactor: "4-Post Enclosure",
  tiFrontClearance: 0.0,
  tiFrontDoorPerforation: 0.0,
  tiFrontRailOffset: 0.0,
  tiHeight: 73.5,
  tiIntegrationStatus: "In dcTrack Only",
  tiLeftClearance: 0.0,
  tiLoadCapacity: 0.0,
  tiMounting: "Free-Standing / 4-Post Enclosure",
  tiPowerCapacity: 0.0,
  tiPowerPortCount: 0,
  tiPurchasePrice: 0.0,
  tiRailWidth: 0.0,
  tiRearClearance: 0.0,
  tiRearDoorPerforation: 0.0,
  tiRearRailOffset: 0.0,
  tiRightClearance: 0.0,
  tiSysCreatedBy: "admin",
  tiWeight: 250.0,
  tiWidth: 24.0,
  chkItemAutoPowerBudget: "false",
  cmbAirflow: "Front to Back",
  tiCpuQuantity: 0,
  tiDiskGB: 0,
  tiItemOriginalPower: 450.0,
  tiPSRedundancy: "N+1",
  tiPortNamePrefix: "PS",
  tiProcesses: 0,
  tiRAM: 0,
  cbPropagate: "",
};
