export const sheet_headers = {
  Locations: [
    "# Operation ",
    "Object ",
    "dcTrack Location Code",
    "dcTrack Location Name",
    "dcTrack Location Hierarchy",
    "dcTrack Location Parent",
    "Can Contain Assets",
    "Data Center Area",
    "Country",
    "Enable AC Virtual Power Chain",
    "Enable DC Virtual Power Chain",
    "Is Default Location",
    "Capacity(kW)",
  ],
  "Aisles and Rows": [
    "# Operation ",
    "Object ",
    "Sub Location Name",
    "Location  ",
    "Sub Location Type",
    "Parent Sub Location",
    "Capacity(kW)",
  ],
  Cabinets: [
    "# Operation ",
    "Object ",
    "Name ",
    "Make ",
    "Model ",
    "Part Number",
    "Location  ",
    "Location Name",
    "Front Faces",
    "Aisle Label  ",
    "Row Label   ",
    "Position in Row    ",
    "Status",
    "Power Capacity (kW)",
    "Weight Capacity",
  ],
  "Rack PDUs": [
    "# Operation ",
    "Object ",
    "Name ",
    "Make ",
    "Model ",
    "Part Number",
    "Location  ",
    "Location Name",
    "Cabinet ",
    "Depth Position ",
    "Cabinet Side ",
    "U Position ",
    "IP Address",
    "IP Address Port Name",
    "SNMP Write Community String",
    "User Name",
    "Password",
    "Status",
  ],
  Devices: [
    "# Operation ",
    "Object ",
    "Name ",
    "Make ",
    "Model ",
    "Part Number",
    "Location  ",
    "Location Name",
    "Asset Tag",
    "Serial Number",
    "Cabinet ",
    "U Position ",
    "Chassis ",
    "Chassis Face ",
    "Slot Position ",
    "Is VM Host",
    "VM Cluster",
    "Status",
  ],
  Power: [
    "# Operation ",
    "Object ",
    "Starting Item Location  ",
    "Starting Item Name ",
    "Starting Port Name  ",
    "Cord Type",
    "Cord ID",
    "Cord Color",
    "Cord Length (ft/m)",
    "Length Units",
    "Ending Item Location ",
    "Ending Item Name  ",
    "Ending Port Name  ",
    "CIRCUIT ID",
    "Contact Team",
    "Contact",
    "Notes",
  ],
  "Structure Cabling": [
    "# Operation ",
    "Object ",
    "Starting Item Location ",
    "Starting Item Name ",
    "Starting Port Name  ",
    "Starting Port Index",
    "Starting Port Connector   ",
    "Cable Grade  ",
    "Media",
    "Length (ft/m) ",
    "Length Units",
    "Color",
    "Group",
    "Ending  Item Location",
    "Ending Item Name  ",
    "Ending Port Name  ",
    "Ending Port Index",
    "Ending Port Connector   ",
  ],
  "Data Connections": [
    "# Operation ",
    "Object ",
    "Starting Item Location  ",
    "Starting Item Name ",
    "Starting Port Name  ",
    "Cord 1 Type",
    "Cord 1 ID",
    "Cord 1 Color",
    "Cord 1 Length( ft/m)",
    "Length Units",
    "Ending Item Location ",
    "Ending Item Name  ",
    "Ending Port Name  ",
    "CIRCUIT ID",
    "Contact Team",
    "Contact",
    "Notes",
  ],
  "Add Power Panels": [
    "# Operation ",
    "Object ",
    "Floor PDU ",
    "Name ",
    "Location  ",
    "Location Name",
    "Phases ",
    "Phase Voltage ",
    "Wire Colors ",
    "Rating (A)",
    "No of Poles ",
    "Panel Layout ",
    "Pole Numbering ",
    "First Pole Number",
    "Mirrored",
  ],
  "Add Breakers & Outlets": [
    "# Operation ",
    "Object ",
    "Panel Type",
    "Floor PDU ",
    "Make",
    "Model",
    "Panel ",
    "Location ",
    "Starting Pole No  ",
    "No of Poles",
    "Rated Amps",
    "Measured Amps",
    "Power Outlet Location",
    "Power Outlet Row",
    "Power Outlet Position in Row",
    "Power Outlet Connector",
    "Power Outlet Cabinet",
    "Power Outlet Position",
  ],
  "Data, Power & Sensor Ports": [
    "# Operation ",
    "Object ",
    "Item Location  ",
    "Item Name ",
    "Port Name  ",
    "Index ",
    "Port Type",
    "In Use",
    "Color Code",
    "Grouping/VLAN",
    "MAC Address",
    "IP Address",
    "Connector  ",
    "Media  ",
    "Protocol  ",
    "Data Rate  ",
    "Comment",
  ],
  "Add Parts": [
    "# Operation ",
    "Object ",
    "Serial/Asset/Batch Number ",
    "Make ",
    "Model ",
    "Part Number ",
    "Storage Location  ",
    "Tracking ",
    "Description",
    "Count in Stock ",
    "Count in Use ",
    "Threshold ",
    "Status ",
    "Date of Manufacture",
    "Date Format",
    "Threshold Contacts",
  ],
};

export const sheet_to_object = {
  Locations: "LOCATION",
  "Aisles and Rows": "SUBLOCATION",
  Cabinets: "CABINET",
  "Rack PDUs": "RACK PDU-ZERO U",
  Devices: "DEVICE-RACKABLE",
  Power: "POWER-CONNECTION",
  "Structure Cabling": "STRUCTURED-CABLING",
  "Data Connections": "DATA-CONNECTION",
  "Add Power Panels": "POWER PANEL-LOCAL",
  "Add Breakers & Outlets": "PANEL BREAKER",
  "Data, Power & Sensor Ports": "DATA-PORT",
  "Add Parts": "PART",
};
