export const header = {
  Locations: {
    "# Operation *": "",
    "Object *": "",
    "dcTrack Location Code*": "",
    "dcTrack Location Name*": "",
    "dcTrack Location Hierarchy*": "",
    "dcTrack Location Parent*": "",
    "Can Contain Assets": "",
    "Data Center Area*": "",
    "Country*": "",
    "Enable AC Virtual Power Chain": "",
    "Enable DC Virtual Power Chain": "",
    "Is Default Location": "",
    "Capacity(kW)": "",
  },
  "Aisles and Rows": {
    "# Operation *": "",
    "Object *": "",
    "Sub Location Name*": "",
    "Location  *": "",
    "Sub Location Type*": "",
    "Parent Sub Location": "",
    "Capacity(kW)": "",
  },
  Cabinets: {
    "# Operation *": "",
    "Object *": "",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location  *": "",
    "Location Name": "",
    "Front Faces": "",
    "Aisle Label  ": "",
    "Row Label   **": "",
    "Position in Row   ** ": "",
    Status: "",
    "Power Capacity (kW)": "",
    "Weight Capacity": "",
  },
  "Rack PDUs": {
    "# Operation *": "",
    "Object *": "",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location  *": "",
    "Location Name": "",
    "Cabinet **": "",
    "Depth Position **": "",
    "Cabinet Side **": "",
    "U Position **": "",
    "IP Address": "",
    "IP Address Port Name": "",
    "SNMP Write Community String": "",
    "User Name": "",
    Password: "",
    Status: "",
  },
  Devices: {
    "# Operation *": "",
    "Object *": "",
    "Name *": "",
    "Make *": "",
    "Model *": "",
    "Part Number": "",
    "Location  *": "",
    "Location Name": "",
    "Asset Tag": "",
    "Serial Number": "",
    "Cabinet **": "",
    "U Position **": "",
    "Chassis **": "",
    "Chassis Face **": "",
    "Slot Position **": "",
    "Is VM Host": "",
    "VM Cluster": "",
    Status: "",
  },
  Power: {
    "# Operation *": "",
    "Object *": "",
    "Starting Item Location  *": "",
    "Starting Item Name *": "",
    "Starting Port Name  *": "",
    "Cord Type": "",
    "Cord ID": "",
    "Cord Color": "",
    "Cord Length (ft/m)": "",
    "Length Units": "",
    "Ending Item Location *": "",
    "Ending Item Name  *": "",
    "Ending Port Name  *": "",
    "CIRCUIT ID": "",
    "Contact Team": "",
    Contact: "",
    Notes: "",
  },
  "Structure Cabling": {
    "# Operation *": "",
    "Object *": "",
    "Starting Item Location *": "",
    "Starting Item Name *": "",
    "Starting Port Name  *": "",
    "Starting Port Index": "",
    "Starting Port Connector  * ": "",
    "Cable Grade  **": "",
    "Media**": "",
    "Length (ft/m) *": "",
    "Length Units": "",
    Color: "",
    Group: "",
    "Ending  Item Location*": "",
    "Ending Item Name  *": "",
    "Ending Port Name  *": "",
    "Ending Port Index": "",
    "Ending Port Connector  * ": "",
  },
  "Data Connections": {
    "# Operation *": "",
    "Object *": "",
    "Starting Item Location  *": "",
    "Starting Item Name *": "",
    "Starting Port Name  *": "",
    "Cord 1 Type": "",
    "Cord 1 ID": "",
    "Cord 1 Color": "",
    "Cord 1 Length( ft/m)": "",
    "Length Units": "",
    "Ending Item Location *": "",
    "Ending Item Name  *": "",
    "Ending Port Name  *": "",
    "CIRCUIT ID": "",
    "Contact Team": "",
    Contact: "",
    Notes: "",
  },
  "Add Power Panels": {
    "# Operation *": "",
    "Object *": "",
    "Floor PDU *": "",
    "Name *": "",
    "Location  *": "",
    "Location Name": "",
    "Phases *": "",
    "Phase Voltage *": "",
    "Wire Colors *": "",
    "Rating (A)*": "",
    "No of Poles *": "",
    "Panel Layout *": "",
    "Pole Numbering *": "",
    "First Pole Number": "",
    Mirrored: "",
  },
  "Add Breakers & Outlets": {
    "# Operation *": "",
    "Object *": "",
    "Panel Type*": "",
    "Floor PDU *": "",
    Make: "",
    Model: "",
    "Panel *": "",
    "Location *": "",
    "Starting Pole No  *": "",
    "No of Poles*": "",
    "Rated Amps*": "",
    "Measured Amps": "",
    "Power Outlet Location**": "",
    "Power Outlet Row**": "",
    "Power Outlet Position in Row**": "",
    "Power Outlet Connector**": "",
    "Power Outlet Cabinet**": "",
    "Power Outlet Position**": "",
  },
  "Data, Power & Sensor Ports": {
    "# Operation *": "",
    "Object *": "",
    "Item Location  *": "",
    "Item Name *": "",
    "Port Name  *": "",
    "Index ": "",
    "Port Type*": "",
    "In Use": "",
    "Color Code": "",
    "Grouping/VLAN": "",
    "MAC Address": "",
    "IP Address": "",
    "Connector  *": "",
    "Media  *": "",
    "Protocol  *": "",
    "Data Rate  *": "",
    Comment: "",
  },
  "Add Parts": {
    "# Operation *": "",
    "Object *": "",
    "Serial/Asset/Batch Number *": "",
    "Make *": "",
    "Model *": "",
    "Part Number *": "",
    "Storage Location  *": "",
    "Tracking *": "",
    Description: "",
    "Count in Stock *": "",
    "Count in Use *": "",
    "Threshold *": "",
    "Status *": "",
    "Date of Manufacture": "",
    "Date Format": "",
    "Threshold Contacts": "",
  },
};

export const headerTypes = {
  Locations: {
    "# Operation *": "Operation",
    "Object *": "Object",
    "dcTrack Location Code*": "String",
    "dcTrack Location Name*": "ORC",
    "dcTrack Location Hierarchy*": "String",
    "dcTrack Location Parent*": "String",
    "Can Contain Assets": "String",
    "Data Center Area*": "String",
    "Country*": "String",
    "Enable AC Virtual Power Chain": "String",
    "Enable DC Virtual Power Chain": "String",
    "Is Default Location": "String",
    "Capacity(kW)": "Number",
  },

  "Aisles and Rows": {
    "# Operation *": "Operation",
    "Object *": "Object",
    "Sub Location Name*": "ORC",
    "Location  *": "String",
    "Sub Location Type*": "String",
    "Parent Sub Location": "String",
    "Capacity(kW)": "Number",
  },

  Cabinets: {
    "# Operation *": "Operation",
    "Object *": "Object",
    "Name *": "ORC",
    "Make *": "IMG",
    "Model *": "IMG",
    "Part Number": "ORC",
    "Location  *": "String",
    "Location Name": "ORC",
    "Front Faces": "Number",
    "Aisle Label  ": "String",
    "Row Label   **": "String",
    "Position in Row   ** ": "Number",
    Status: "String",
    "Power Capacity (kW)": "Number",
    "Weight Capacity": "Number",
  },

  "Rack PDUs": {
    "# Operation *": "Operation",
    "Object *": "Object",
    "Name *": "ORC",
    "Make *": "IMG",
    "Model *": "IMG",
    "Part Number": "ORC",
    "Location  *": "String",
    "Location Name": "ORC",
    "Cabinet **": "String",
    "Depth Position **": "Number",
    "Cabinet Side **": "String",
    "U Position **": "Number",
    "IP Address": "String",
    "IP Address Port Name": "String",
    "SNMP Write Community String": "String",
    "User Name": "String",
    Password: "String",
    Status: "String",
  },

  Devices: {
    "# Operation *": "Operation",
    "Object *": "Object",
    "Name *": "ORC",
    "Make *": "IMG",
    "Model *": "IMG",
    "Part Number": "ORC",
    "Location  *": "String",
    "Location Name": "ORC",
    "Asset Tag": "QR",
    "Serial Number": "QR",
    "Cabinet **": "String",
    "U Position **": "Number",
    "Chassis **": "String",
    "Chassis Face **": "String",
    "Slot Position **": "Number",
    "Is VM Host": "String",
    "VM Cluster": "String",
    Status: "String",
  },

  Power: {
    "# Operation *": "Operation",
    "Object *": "Object",
    "Starting Item Location  *": "String",
    "Starting Item Name *": "ORC",
    "Starting Port Name  *": "ORC",
    "Cord Type": "String",
    "Cord ID": "QR",
    "Cord Color": "String",
    "Cord Length (ft/m)": "Number",
    "Length Units": "String",
    "Ending Item Location *": "String",
    "Ending Item Name  *": "ORC",
    "Ending Port Name  *": "ORC",
    "CIRCUIT ID": "String",
    "Contact Team": "String",
    Contact: "String",
    Notes: "String",
  },

  "Structure Cabling": {
    "# Operation *": "Operation",
    "Object *": "Object",
    "Starting Item Location *": "String",
    "Starting Item Name *": "ORC",
    "Starting Port Name  *": "ORC",
    "Starting Port Index": "Number",
    "Starting Port Connector  * ": "String",
    "Cable Grade  **": "String",
    "Media**": "String",
    "Length (ft/m) *": "Number",
    "Length Units": "String",
    Color: "String",
    Group: "String",
    "Ending  Item Location*": "String",
    "Ending Item Name  *": "ORC",
    "Ending Port Name  *": "ORC",
    "Ending Port Index": "Number",
    "Ending Port Connector  * ": "String",
  },

  "Data Connections": {
    "# Operation *": "Operation",
    "Object *": "Object",
    "Starting Item Location  *": "String",
    "Starting Item Name *": "ORC",
    "Starting Port Name  *": "ORC",
    "Cord 1 Type": "String",
    "Cord 1 ID": "QR",
    "Cord 1 Color": "String",
    "Cord 1 Length( ft/m)": "Number",
    "Length Units": "String",
    "Ending Item Location *": "String",
    "Ending Item Name  *": "ORC",
    "Ending Port Name  *": "ORC",
    "CIRCUIT ID": "String",
    "Contact Team": "String",
    Contact: "String",
    Notes: "String",
  },

  "Add Power Panels": {
    "# Operation *": "Operation",
    "Object *": "Object",
    "Floor PDU *": "String",
    "Name *": "ORC",
    "Location  *": "String",
    "Location Name": "ORC",
    "Phases *": "Number",
    "Phase Voltage *": "Number",
    "Wire Colors *": "String",
    "Rating (A)*": "Number",
    "No of Poles *": "Number",
    "Panel Layout *": "String",
    "Pole Numbering *": "String",
    "First Pole Number": "Number",
    Mirrored: "String",
  },

  "Add Breakers & Outlets": {
    "# Operation *": "Operation",
    "Object *": "Object",
    "Panel Type*": "String",
    "Floor PDU *": "String",
    Make: "IMG",
    Model: "IMG",
    "Panel *": "String",
    "Location *": "String",
    "Starting Pole No  *": "Number",
    "No of Poles*": "Number",
    "Rated Amps*": "Number",
    "Measured Amps": "Number",
    "Power Outlet Location**": "String",
    "Power Outlet Row**": "Number",
    "Power Outlet Position in Row**": "Number",
    "Power Outlet Connector**": "String",
    "Power Outlet Cabinet**": "String",
    "Power Outlet Position**": "Number",
  },

  "Data, Power & Sensor Ports": {
    "# Operation *": "Operation",
    "Object *": "Object",
    "Item Location  *": "String",
    "Item Name *": "ORC",
    "Port Name  *": "ORC",
    "Index ": "Number",
    "Port Type*": "String",
    "In Use": "String",
    "Color Code": "String",
    "Grouping/VLAN": "String",
    "MAC Address": "String",
    "IP Address": "String",
    "Connector  *": "String",
    "Media  *": "String",
    "Protocol  *": "String",
    "Data Rate  *": "Number",
    Comment: "String",
  },

  "Add Parts": {
    "# Operation *": "Operation",
    "Object *": "Object",
    "Serial/Asset/Batch Number *": "QR",
    "Make *": "IMG",
    "Model *": "IMG",
    "Part Number *": "ORC",
    "Storage Location  *": "String",
    "Tracking *": "String",
    Description: "String",
    "Count in Stock *": "Number",
    "Count in Use *": "Number",
    "Threshold *": "Number",
    "Status *": "String",
    "Date of Manufacture": "String",
    "Date Format": "String",
    "Threshold Contacts": "String",
  },
};

export const headerDescriptions = {
  Locations: {
    "# Operation *":
      "Defines whether this row will create, update, or delete a Location record in dcTrack. Auditors typically use CREATE for new locations and UPDATE when adjusting names, hierarchy, or properties. Required for all import rows.",
    "Object *":
      "Specifies the object type being imported. For this sheet the value is always LOCATION. dcTrack uses this to determine how the row will be processed during import.",
    "dcTrack Location Code*":
      "The unique location code used throughout dcTrack. Must follow your site naming standard. This code appears in Location pickers, power chain views, and asset placement workflows.",
    "dcTrack Location Name*":
      "Human readable name of the location. Auditors typically use the physical data center name or building identifier. This is what end users see in navigation trees.",
    "dcTrack Location Hierarchy*":
      "The full hierarchical path showing where this location sits inside the global structure. Example: Region / Country / Campus / Building / Floor / Room. Must match existing nodes in hierarchy.",
    "dcTrack Location Parent*":
      "The direct parent of this location. Ensures proper placement in the location tree. Auditors must confirm parent nodes exist before load.",
    "Can Contain Assets":
      "Indicates whether devices and cabinets can be directly assigned to this location. Enable when the location represents an actual placement zone like a room or cage.",
    "Data Center Area*":
      "Defines the physical area type such as DATA CENTER, CLOSET, LAB, or OFFICE. Used for capacity reporting and analytics.",
    "Country*": "Country where the location resides. Important for compliance, reporting, and global multi-site filtering.",
    "Enable AC Virtual Power Chain":
      "If enabled, dcTrack will generate a virtual AC chain for locations where actual power infrastructure is not modeled. Useful for high-level auditing.",
    "Enable DC Virtual Power Chain": "Equivalent to AC Virtual Power Chain, but for DC-powered environments.",
    "Is Default Location":
      "Marks this location as the system default for new items created without an assigned location. Typically only one location should be marked this way.",
    "Capacity(kW)": "Optional overall power capacity for the location. Used in reporting and capacity forecasts.",
  },

  "Aisles and Rows": {
    "# Operation *":
      "Defines whether the row creates, updates, or deletes a Sub-Location (Aisle or Row). Required for every import row.",
    "Object *": "For this sheet the value is always SUBLOCATION. dcTrack uses this to create aisle or row objects.",
    "Sub Location Name*": "Name of the aisle or row. Should follow site standards such as A1, A2, ROW-01, etc.",
    "Location  *": "The parent Location this aisle or row belongs to. Must exist in the Locations sheet.",
    "Sub Location Type*": "Indicates AISLE or ROW. Determines where cabinets may be positioned in layout views.",
    "Parent Sub Location":
      "If this sublocation falls under another sublocation (Row under Aisle), define it here. Enables nested structure.",
    "Capacity(kW)": "Optional aggregate power capacity available for assets placed within this aisle or row.",
  },

  Cabinets: {
    "# Operation *": "Defines whether to create, update, or delete a Cabinet record. Required on all rows.",
    "Object *": "For this sheet the value is CABINET. Used by dcTrack to identify the item type.",
    "Name *": "The cabinet name. Typically the label applied to the rack (example: R1-01). Must be unique within the site.",
    "Make *": "The cabinet manufacturer such as APC, Chatsworth, Great Lakes, or Rittal. Used for dimensions and mounting rules.",
    "Model *": "Exact manufacturer model. Determines size, doors, mounting depth options, and available U-space.",
    "Part Number": "Vendor specific part number for the cabinet. Optional but useful for procurement and change verification.",
    "Location  *": "The parent location such as ROOM-101. Must match a Location defined in the Locations sheet.",
    "Location Name":
      "Human readable location name. Used for visual navigation. Must be consistent with existing naming standards.",
    "Front Faces":
      "Specifies whether the cabinet front faces North, South, East, or West in room layout views. Required for accurate floor plans.",
    "Aisle Label  ": "Associates the cabinet with an aisle. Required when modeling hot or cold aisle containment.",
    "Row Label   **": "Row identifier the cabinet belongs to. Enables cabinet sequencing and layout correctness.",
    "Position in Row   ** ": "Numeric position of the cabinet within the row. Determines left-to-right ordering in dcTrack.",
    Status:
      "Current cabinet status such as ACTIVE, PLANNED, RESERVED, or DECOMMISSIONED. Affects visibility during asset placement.",
    "Power Capacity (kW)": "Total power capacity available to the cabinet. Used for power planning and load balancing.",
    "Weight Capacity": "Maximum allowable load for the cabinet. Important for auditing heavy servers or PDUs.",
  },

  "Rack PDUs": {
    "# Operation *": "Defines create, update, or delete for a Rack PDU record.",
    "Object *": "For this sheet the object type is RACK PDU-ZERO U. Identifies vertical rack PDUs.",
    "Name *": "Rack PDU name. Typically matches the label applied in the field such as PDU-L1 or PDU-R1.",
    "Make *": "Device manufacturer such as APC, ServerTech, Eaton, or Geist.",
    "Model *": "Exact model. Determines outlet count, outlet type, and capabilities such as metering.",
    "Part Number": "Vendor part number for procurement tracking.",
    "Location  *": "Parent room or location for the PDU.",
    "Location Name": "Readable name associated with the location.",
    "Cabinet **": "The cabinet the PDU is mounted in. Required for proper placement in layout views.",
    "Depth Position **": "Defines front, middle, or rear mounting depth depending on the PDU installation.",
    "Cabinet Side **": "Left or right side of the cabinet where the PDU is mounted.",
    "U Position **": "U-position where the PDU begins. Required for consistent visualization.",
    "IP Address": "Management IP. Required for integration with PowerIQ or polling.",
    "IP Address Port Name": "Port name associated with the IP interface.",
    "SNMP Write Community String": "Required only for writable SNMP PDUs. Used to control outlet switching.",
    "User Name": "Username for authenticated PDU access.",
    Password: "Password for authenticated PDU access.",
    Status: "Operational state of the PDU such as ACTIVE, PLANNED, or UNAVAILABLE.",
  },

  Devices: {
    "# Operation *": "Defines create, update, or delete for a Device record.",
    "Object *": "Object type for rack-mountable assets is DEVICE-RACKABLE.",
    "Name *": "Device name in dcTrack. Should match physical labels (example: SRV-101).",
    "Make *": "Manufacturer such as Dell, HPE, Cisco. Used by auto-model selection.",
    "Model *": "Exact model. Determines size, power ports, data ports, and mounting options.",
    "Part Number": "Vendor part number. Optional but recommended for procurement linking.",
    "Location  *": "Parent location for this asset if not yet placed in a cabinet.",
    "Location Name": "Readable name for the assigned location.",
    "Asset Tag": "Unique tag assigned by the organization. Required for tracking, audits, and reconciliation.",
    "Serial Number": "Manufacturer serial. Critical for inventory management and warranty validation.",
    "Cabinet **": "Cabinet where the device is installed. Required when the device is racked.",
    "U Position **": "The starting rack unit where the device is mounted.",
    "Chassis **": "If the device is a blade or module, identifies the parent chassis.",
    "Chassis Face **": "Defines the chassis face (front or rear) where the module is inserted.",
    "Slot Position **": "Slot index inside a chassis where this module resides.",
    "Is VM Host": "Flags the device as a virtualization host. Enables VM view integration.",
    "VM Cluster": "Cluster name if the device is part of a virtualized cluster.",
    Status: "Operational status such as ACTIVE, PLANNED, or DECOMMISSIONED.",
  },

  Power: {
    "# Operation *": "Defines create, update, or delete for a power connection record.",
    "Object *": "Object type is POWER-CONNECTION. Used to model each end-to-end power link.",
    "Starting Item Location  *": "Location of the device where the power chain begins.",
    "Starting Item Name *": "The originating device name such as a server or cabinet PDU.",
    "Starting Port Name  *": "The specific power input port where the connection starts.",
    "Cord Type": "Cable type (C13-C14, C19-C20, L6-30P, etc.). Needed for validation.",
    "Cord ID": "Label applied to the power cord for traceability.",
    "Cord Color": "Physical color of the cord used for redundancy differentiation.",
    "Cord Length (ft/m)": "Cord length. Helps auditors confirm proper fit and compliance.",
    "Length Units": "Units used for cable length, FT or M.",
    "Ending Item Location *": "Location of the item where the connection ends.",
    "Ending Item Name  *": "Name of the target device or PDU outlet.",
    "Ending Port Name  *": "Name of the specific port at the destination.",
    "CIRCUIT ID": "Identifier for the electrical circuit. Required for AC chain mapping.",
    "Contact Team": "Ops team responsible for the circuit or installation.",
    Contact: "Person to contact for questions or escalation.",
    Notes: "Optional comments for documentation of special routing or compliance notes.",
  },

  "Structure Cabling": {
    "# Operation *": "Defines create, update, or delete for a structured cabling connection.",
    "Object *": "Object type is STRUCTURED-CABLING.",
    "Starting Item Location *": "Location where the cable originates.",
    "Starting Item Name *": "The panel, switch, or device where the cable starts.",
    "Starting Port Name  *": "Exact port name serving as the starting endpoint.",
    "Starting Port Index": "Numeric index for ordered ports. Optional unless standardized.",
    "Starting Port Connector  * ": "Connector type such as LC, RJ45, QSFP. Required for validation.",
    "Cable Grade  **": "Cable type such as CAT6A, OM4, OS2. Required for planning.",
    "Media**": "Copper or Fiber. Must match port capabilities.",
    "Length (ft/m) *": "Cable length. Required for structured wiring.",
    "Length Units": "FT or M.",
    Color: "Color used for cable management standards.",
    Group: "Logical or physical grouping. Optional.",
    "Ending  Item Location*": "Where the cable terminates.",
    "Ending Item Name  *": "Name of the target device or panel.",
    "Ending Port Name  *": "Exact port name where the connection ends.",
    "Ending Port Index": "Index of the destination port.",
    "Ending Port Connector  * ": "Connector type matching the endpoint hardware.",
  },

  "Data Connections": {
    "# Operation *": "Defines create, update, or delete for a data cable connection.",
    "Object *": "Object type is DATA-CONNECTION.",
    "Starting Item Location  *": "Location of the originating device.",
    "Starting Item Name *": "Device or panel name where the data link starts.",
    "Starting Port Name  *": "Name of the starting data port.",
    "Cord 1 Type": "Cable category or fiber type used.",
    "Cord 1 ID": "Label applied to the first cord for tracking.",
    "Cord 1 Color": "Cord color for visual identification.",
    "Cord 1 Length( ft/m)": "Cable length.",
    "Length Units": "FT or M.",
    "Ending Item Location *": "Location where the link terminates.",
    "Ending Item Name  *": "Device or panel at the destination.",
    "Ending Port Name  *": "Exact data port name at the endpoint.",
    "CIRCUIT ID": "Circuit or patch ID for data links. Optional depending on standards.",
    "Contact Team": "Team responsible for maintaining the data connection.",
    Contact: "Individual point of contact for audits or issues.",
    Notes: "Optional notes for cable routing or exceptions.",
  },

  "Add Power Panels": {
    "# Operation *": "Defines create, update, or delete for a Power Panel record.",
    "Object *": "Object type is POWER PANEL-LOCAL.",
    "Floor PDU *": "Floor-mounted PDU feeding this panel. Must exist in dcTrack.",
    "Name *": "Power panel label. Must match physical field label.",
    "Location  *": "Location of the panel. Required for hierarchy mapping.",
    "Location Name": "Human readable location name.",
    "Phases *": "Number of electrical phases: 1 or 3. Must match physical panel.",
    "Phase Voltage *": "Voltage rating such as 208V or 415V.",
    "Wire Colors *": "Wire color coding standard used in the panel.",
    "Rating (A)*": "Panel amperage rating.",
    "No of Poles *": "Total number of breaker slots available.",
    "Panel Layout *": "Defines physical order such as STANDARD or MIRRORED.",
    "Pole Numbering *": "Determines numbering sequence such as SEQUENTIAL or ODD/EVEN.",
    "First Pole Number": "The lowest pole number in the panel.",
    Mirrored: "Indicates whether the physical layout is mirrored relative to standard.",
  },

  "Add Breakers & Outlets": {
    "# Operation *": "Defines create, update, or delete for a breaker or outlet record.",
    "Object *": "Object type is PANEL BREAKER.",
    "Panel Type*": "Type of panel such as AC or DC.",
    "Floor PDU *": "PDU that energizes the panel.",
    Make: "Manufacturer of the breaker or outlet module.",
    Model: "Model identifier for the breaker or outlet.",
    "Panel *": "Name of the associated panel. Must exist prior to import.",
    "Location *": "Location of the panel or outlet.",
    "Starting Pole No  *": "Pole where the breaker begins.",
    "No of Poles*": "Breaker size in poles such as 1P, 2P, or 3P.",
    "Rated Amps*": "Breaker amperage rating.",
    "Measured Amps": "Actual measured current. Optional.",
    "Power Outlet Location**": "Location of the associated outlet if applicable.",
    "Power Outlet Row**": "Row of the outlet placement.",
    "Power Outlet Position in Row**": "Position within the row.",
    "Power Outlet Connector**": "Connector type available.",
    "Power Outlet Cabinet**": "Cabinet associated with the outlet.",
    "Power Outlet Position**": "Cabinet position for the outlet.",
  },

  "Data, Power & Sensor Ports": {
    "# Operation *": "Defines create, update, or delete for a port record.",
    "Object *": "Object type is DATA-PORT.",
    "Item Location  *": "Location of the item that owns the port.",
    "Item Name *": "Device or item that the port belongs to.",
    "Port Name  *": "Exact name of the port such as Gi1/0/1 or PWR1.",
    "Index ": "Numeric port index. Used for ordering.",
    "Port Type*": "Type such as DATA, POWER, SENSOR, FIBER, ETHERNET.",
    "In Use": "Defines whether the port is actively used or free.",
    "Color Code": "Color code assigned for visual cable management.",
    "Grouping/VLAN": "Logical grouping or VLAN for data ports.",
    "MAC Address": "MAC address associated with the port when applicable.",
    "IP Address": "Assigned IP address for management ports.",
    "Connector  *": "Connector type: RJ45, LC, SC, C13, etc.",
    "Media  *": "Fiber or Copper.",
    "Protocol  *": "Communication protocol such as Ethernet, Fibre Channel.",
    "Data Rate  *": "Port speed such as 1Gb, 10Gb, 40Gb, etc.",
    Comment: "Optional free-text used by auditors to document exceptions.",
  },

  "Add Parts": {
    "# Operation *": "Defines create, update, or delete for a Part record.",
    "Object *": "Object type is PART.",
    "Serial/Asset/Batch Number *": "Unique identifier for the part. Required.",
    "Make *": "Manufacturer of the part.",
    "Model *": "Model identifier assigned by manufacturer.",
    "Part Number *": "Vendor part number. Required for cataloging.",
    "Storage Location  *": "Location where the part is stored. Must exist as a Location.",
    "Tracking *": "Tracking method such as Individual, Batch, or Not Tracked.",
    Description: "Explanation of what the part is and how it is used.",
    "Count in Stock *": "Quantity currently in inventory.",
    "Count in Use *": "Number of units currently deployed.",
    "Threshold *": "Minimum quantity before replenishment alerts trigger.",
    "Status *": "Operational status such as ACTIVE or RETIRED.",
    "Date of Manufacture": "Manufacturing date if applicable.",
    "Date Format": "Date format used for the manufacture date.",
    "Threshold Contacts": "Contacts responsible for restocking or threshold alerts.",
  },
};
